
# Sources  
SET(TEST_SOURCES_SINGLE_SEQ ${CMAKE_CURRENT_LIST_DIR}/iB_Real_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runRealSingleSeq.cpp)

SET(TEST_SOURCES_DOUBLE_SEQ ${CMAKE_CURRENT_LIST_DIR}/iB_Real_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runRealDoubleSeq.cpp)

SET(TEST_SOURCES_SINGLE_RND ${CMAKE_CURRENT_LIST_DIR}/iB_Real_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runRealSingleRnd.cpp)

SET(TEST_SOURCES_DOUBLE_RND ${CMAKE_CURRENT_LIST_DIR}/iB_Real_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runRealDoubleRnd.cpp)

SET(TEST_SOURCES_COMPLEX_SINGLE_SEQ ${CMAKE_CURRENT_LIST_DIR}/iB_Complex_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runComplexSingleSeq.cpp)

SET(TEST_SOURCES_COMPLEX_SINGLE_RND ${CMAKE_CURRENT_LIST_DIR}/iB_Complex_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runComplexSingleRnd.cpp)

SET(TEST_SOURCES_COMPLEX_DOUBLE_SEQ ${CMAKE_CURRENT_LIST_DIR}/iB_Complex_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runComplexDoubleSeq.cpp)

SET(TEST_SOURCES_COMPLEX_DOUBLE_RND ${CMAKE_CURRENT_LIST_DIR}/iB_Complex_FFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runComplexDoubleRnd.cpp)

# Include directory 
SET(TEST_HEADERS_DIR ${CMAKE_CURRENT_LIST_DIR}/inc)

# Add kernels to the include files 
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/Kernels)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/..)

# Add the include directory to the source tree 
INCLUDE_DIRECTORIES(${TEST_HEADERS_DIR})

# Generate the executables
CUDA_ADD_EXECUTABLE(iB_RealSingleSeq_FFTShift_2D ${TEST_SOURCES_SINGLE_SEQ} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_RealDoubleSeq_FFTShift_2D ${TEST_SOURCES_DOUBLE_SEQ} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_RealSingleRnd_FFTShift_2D ${TEST_SOURCES_SINGLE_RND} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_RealDoubleRnd_FFTShift_2D ${TEST_SOURCES_DOUBLE_RND} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_ComplexSingleSeq_FFTShift_2D ${TEST_SOURCES_COMPLEX_SINGLE_SEQ} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_ComplexSingleRnd_FFTShift_2D ${TEST_SOURCES_COMPLEX_SINGLE_RND} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_ComplexDoubleSeq_FFTShift_2D ${TEST_SOURCES_COMPLEX_DOUBLE_SEQ} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_ComplexDoubleRnd_FFTShift_2D ${TEST_SOURCES_COMPLEX_DOUBLE_RND} ${SOURCES} ${CUDA_SOURCES})

