
# Sources  
SET(TEST_SOURCES_SINGLE ${CMAKE_CURRENT_LIST_DIR}/iB_cuFFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runRealSingle.cpp)

SET(TEST_SOURCES_DOUBLE ${CMAKE_CURRENT_LIST_DIR}/iB_cuFFTShift_2D.cpp
		 ${CMAKE_CURRENT_LIST_DIR}/runRealDouble.cpp)

# Include directory 
SET(TEST_HEADERS_DIR ${CMAKE_CURRENT_LIST_DIR}/inc)

# Add kernels to the include files 
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/Kernels)

# Add the include directory to the source tree 
INCLUDE_DIRECTORIES(${TEST_HEADERS_DIR})

# Generate the executables
CUDA_ADD_EXECUTABLE(iB_RealSingleFFTShift_2D ${TEST_SOURCES_SINGLE} ${SOURCES} ${CUDA_SOURCES})
CUDA_ADD_EXECUTABLE(iB_RealDoubleFFTShift_2D ${TEST_SOURCES_DOUBLE} ${SOURCES} ${CUDA_SOURCES})
